version: '3.8'

services:
  simulation-engine:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HYPEREVM_RPC_URL=${HYPEREVM_RPC_URL:-https://sepolia.drpc.org}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - REQUEST_TIMEOUT_MS=${REQUEST_TIMEOUT_MS:-30000}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-10mb}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot reload
  simulation-engine-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - HYPEREVM_RPC_URL=${HYPEREVM_RPC_URL:-https://sepolia.drpc.org}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    profiles:
      - dev
